### PR TITLE
increase line length

### PR DESCRIPTION
**Pull request by namemcguffin**
increases line limit for YAPF formatting to 120 characters

## Description
changes `column_limit` setting in `.style.yapf` file to 120
formatted all files accordingly

## Motivation and Context
increase line limit for ease of use

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by krubenok — APPROVED** [review]
🎉

So would your suggestion be that stuff gets piecemeal changed to actually be 120 as we touch lines or files and never do it all at once? 

Personally I'd rather rip the bandaid off and do it all in this PR.

**Comment by namemcguffin** [comment]
i think it would be best to wait on merging this until the work on the PRs we want to include in the next version release get merged
just because it would make all these PRs need to format (and thus change) a bunch of files that they dont actually want to touch

**Comment by namemcguffin** [comment]
i think the best solution here is wait until we finish on merging everything that's intended for the next release into dev, then pull dev into this, run YAPF with the new style, then merge this into dev and finally merge dev into main

**Comment by krubenok** [comment]
I don't see why we can't format in this PR to dev, then just make the outstanding PR's format their changes after they pull new formatted dev back into their branches.

**Comment by namemcguffin** [comment]
oh yeah thats fair, didnt think about that lol

**Pull request closed without merging**
