### PR TITLE
New functions, documentation, and code refactor

### PR DESCRIPTION
**Pull request by trungams**
- Logging (Val, Trung)
- Code refactor and cleanup (David, patate, yapf)
- Asynchronous requests (Imad)
- GPL license, github templates, contribution guidelines
- ?bac command (Val)
- poll.py (patate)
- bug fixes and misc improvement (Marie, koz)

### CODE REVIEW

**Comment by le-potate** [comment]
Just clarifying that this does not contain `poll.py` as it was reverted, and wasn't put back in dev as I am still working on some changes

**Comment by le-potate** [comment]
@trungams Do we still want to put LogLevel to info? Just saw it wasn't changed

**Comment by le-potate** [comment]
@davidlougheed See 83bbeb9368bf55e44f911c8cde6b4b6163adda99, I didn't add descriptions for currency related values from config.ini because I didn't know what most of them where for, so you might want to add them (or not as these are not essential values to change anyways)

**Comment by le-potate** [comment]
Also, I think that the function for greetings was removed completely, but there is still a section for it in the `config.ini` file

**Comment by trungams** [comment]
everything server related is up to you guys to decide :wink:

**Comment by le-potate** [comment]
Alright well after David decides if he writes descriptions for currency and the readme is reviewed this should be good to go

**Comment by trungams** [comment]
Let me know when the PR goes through. I need to edit things on the server as well, since this change will bring in conflicts, at least to config.ini

**Comment by le-potate** [comment]
@trungams David confirmed that he'll write descriptions so this should be ready to merge tonight or tomorrow

**Comment by le-potate** [comment]
@trungams There you go

**Pull request merged**
