### PR TITLE
Create LICENSE.txt

### PR DESCRIPTION
**Pull request by trungams**
GPL license as requested in #91

### CODE REVIEW

**Comment by trungams** [comment]
review me daddies

**Comment by jidicula** [comment]
@trungams each file in the repo will require the GPL license header as well. See [this page](https://www.gnu.org/licenses/gpl-howto.en.html) for details.

**Comment by trungams** [comment]
@jidicula oh ok. Does that include config files like `.travis.yml`, `config.ini`, or `__init__.py`?

**Comment by jidicula** [comment]
Yeah, let's include it in all of them for consistency.

**Comment by trungams** [comment]
https://opensource.stackexchange.com/questions/5049/licensing-of-configuration-files-that-are-technically-code

Since we're using version GPLv3, I'll just include wherever is necessary to run the bot. Let me know if I'm missing any file

**Comment by jidicula** [comment]
Sounds good, thanks!

**Pull request merged**
